volumes:
  pg_data:
    driver: local

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-18}
    container_name: debt_postgres
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql
  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5