[project]
name = "debt-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kij1n", email = "kij1n@proton.me" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
debt-api = "debt_api:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
